import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getGlobalData } from "@/data/loaders";
import { Header } from "@/components/ui/custom/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globaldata = await getGlobalData();
  console.log(globaldata);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header data={globaldata.header} />
        <div>{children}</div></body>
    </html>
  );
}
